name: release
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - goos: linux
            goarch: amd64
            output: mcserverkit
            zip: mcserverkit-linux-x64.zip
          - goos: windows
            goarch: amd64
            output: mcserverkit.exe
            zip: mcserverkit-windows-x64.zip
          - goos: darwin
            goarch: amd64
            output: mcserverkit
            zip: mcserverkit-macos-x64.zip
          - goos: darwin
            goarch: arm64
            output: mcserverkit
            zip: mcserverkit-macos-arm64.zip
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: go build -o ${{ matrix.output }} ./src
      - name: zip
        run: zip ${{ matrix.zip }} ${{ matrix.output }}
      - name: upload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload "${{ github.event.release.tag_name }}" ${{ matrix.zip }}
